/**
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    /**
     * @return true.
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
